name: Deploy to FTP

on:
  push:
    branches:
      - main  # Ou a branch que você deseja usar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload files to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          local-dir: ./  # Diretório local dos arquivos que você quer enviar
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ # Diretório remoto onde os arquivos devem ser enviados

